### PR TITLE
import without namespace was using the wrong name to trigger the method

### PR DESCRIPTION
**Pull request by nebukadhezer**
Hi Denis,

had a logical error in there.

Cheers
johannes

### CODE REVIEW

**Comment by nebukadhezer** [comment]
Please merge, we need this to get animation in properly.
And why is the [sg_task_order] everywhere ??
It does not work in the current release of the app, wait for the next release of the multi workfiles app and then we can use this... till then it just fails...

Traceback (most recent call last):
File "/srv/projects/rts/WG/Shotgun_Studio/install/frameworks/app_store/tk-framework-widget/v0.2.2/python/browser_widget/browser_widget.py", line 427, in _on_worker_signal
 self.process_result(data)
 File "/srv/projects/rts/WG/Shotgun_Studio/install/apps/app_store/tk-multi-workfiles/v0.6.2/python/tk_multi_workfiles/task_browser.py", line 164, in process_result
     name_extension = ", ".join([d.get(f) for f in extra_fields])
 TypeError: sequence item 0: expected string, int found
 Traceback (most recent call last):
   File "/srv/projects/rts/WG/Shotgun_Studio/install/frameworks/app_store/tk-framework-widget/v0.2.2/python/browser_widget/browser_widget.py", line 427, in _on_worker_signal
     self.process_result(data)
   File "/srv/projects/rts/WG/Shotgun_Studio/install/apps/app_store/tk-multi-workfiles/v0.6.2/python/tk_multi_workfiles/task_browser.py", line 164, in process_result
     name_extension = ", ".join([d.get(f) for f in extra_fields])
 TypeError: sequence item 0: expected string, int found

**Comment by nebukadhezer** [comment]
I did not mean to make that super bold, sorry for that, no yelling. 
Cheers Johannes

**Comment by DenTas** [comment]
hi, we add that to check more easily.  On our side, It works well but I think we add more code outside to solve that. We disable that for now.

**Comment by nebukadhezer** [comment]
You mean  [sg_task_order]  works at your end ? When you use the change context app ?
Or are you referring to sth else ?

**Comment by mattaias** [comment]
Yes, this works at Walking... because we added a "str()" inside of the script some months ago...
I totally forgot about this, so it's good you let them know at shotgun.
I'll try to check what script was changed tomorrow (please let me know if this is still necessary).

Good luck, I'll be back tomorrow.
M.

**Comment by nebukadhezer** [comment]
Ahhh ok they merged my pullrequest, but there is no new release yet.
Check here https://github.com/shotgunsoftware/tk-multi-workfiles/pull/19
So once there is a release we can use this again, if all multi workfiles apps are on the new version then...
it does basically the same.

Cheers
Johannes

**Pull request merged**
